### PR TITLE
use sentry for the ssr service

### LINKED ISSUE #5783: Sentry is not configured for the SSR service
Within the Node-based SSR service, uncaught exceptions are not captured by Sentry. Sentry has a Node-based SDK, so we should be using Sentry for the SSR service as well.

### PR DESCRIPTION
**Pull request by escattone**
Fixes #5783 

This PR enables Sentry for the `ssr` service, so uncaught exceptions are now captured by Sentry.

The `package.json` and `package-lock.json` files were auto-generated from doing `npm install @sentry/node`.

### CODE REVIEW

**Comment by escattone** [comment]
An `infra` companion to this PR has already been merged (see https://github.com/mdn/infra/pull/288), and this PR is already in place on stage (although I haven't actually triggered an uncaught exception yet on the stage `ssr` service).

File: kuma/javascript/ssr-server.js [hunk 1]
```diff
@@ -13,6 +13,21 @@ if (process.env.NEW_RELIC_LICENSE_KEY && process.env.NEW_RELIC_APP_NAME) {
     require('newrelic');
 }
 
+if (process.env.SENTRY_DSN) {
+    console.log('Configuring Sentry for the SSR server.');
+    const Sentry = require('@sentry/node');
```
Comment (peterbe) [inline kuma/javascript/ssr-server.js]: I don't know how I like this. I'd rather this was move outside the if statement so that we know for sure that the `require` works even if you don't configure and call `.init(options)` on it.

Comment (peterbe) [reply kuma/javascript/ssr-server.js]: Actually, what I'd like to is move ALL of this code *except* the line `const Sentry = require('@sentry/node');` to somewhere further down after all the `require()` stuff has happened.

Comment (escattone) [reply kuma/javascript/ssr-server.js]: I'll do that.

**Comment by peterbe** [comment]
Will it definitely use the same DSN that you use for Python/Django? Do I just need to add it `SENTRY_DSN` to my `.env` and then get Sentry for both the Django code *and* the Node code?

**Comment by escattone** [comment]
> Will it definitely use the same DSN that you use for Python/Django? Do I just need to add it `SENTRY_DSN` to my `.env` and then get Sentry for both the Django code _and_ the Node code?

Yes.

**Comment by escattone** [comment]
Successfully tested on stage. 🎉
